version: '3.8'

services:
  # ===========================================
  # ТЕСТОВОЕ ОКРУЖЕНИЕ
  # ===========================================
  investment-service-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investment-data-loader-service-test
    env_file:
      - .env.test
    environment:
      # Профиль
      SPRING_PROFILES_ACTIVE: test

      SPRING_DATASOURCE_TEST_URL: jdbc:postgresql://host.docker.internal:5434/postgres
      SPRING_DATASOURCE_TEST_USERNAME: postgres
      SPRING_DATASOURCE_TEST_PASSWORD: 123password123
      
      # Настройки JVM для контейнера
      JAVA_OPTS: "-Xmx256m -Xms128m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
      
      # DevTools настройки для hot reload
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
    ports:
      - "8087:8087"
    volumes:
      # Volume mapping для hot reload
      - ./src:/app/src
      - ./target:/app/target
      - ./src/main/resources:/app/src/main/resources
      # Копируем .env файл для загрузки переменных
      - ./.env.test:/app/.env:ro
    restart: unless-stopped
    # Лимит памяти: 4 ГБ
    mem_limit: 4g
    mem_reservation: 4g
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ===========================================
  # ПРОДАКШН ОКРУЖЕНИЕ
  # ===========================================
  investment-service-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investment-data-loader-service-prod
    env_file:
      - .env.prod
    environment:
      # Профиль
      SPRING_PROFILES_ACTIVE: prod
      
      # Настройки JVM для контейнера
      JAVA_OPTS: "-Xmx1024m -Xms512m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
      
      # DevTools отключены в продакшне
      SPRING_DEVTOOLS_RESTART_ENABLED: "false"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "false"
    ports:
      - "8083:8083"
    volumes:
      # Только конфигурационные файлы
      - ./src/main/resources:/app/src/main/resources
      # Копируем .env файл для загрузки переменных
      - ./.env.prod:/app/.env:ro
    restart: unless-stopped
    # Лимит памяти: 4 ГБ
    mem_limit: 4g
    mem_reservation: 4g
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - production

