services:
  # Spring Boot приложение
  investment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investment-data-loader-service
    environment:
      # Подключение к внешней PostgreSQL БД
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5434/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123password123
      
      # Токен Tinkoff API (должен быть установлен в .env файле)
      T_INVEST_TOKEN: ${T_INVEST_TOKEN}
      
      # Настройки JVM для контейнера
      JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
      
      # Дополнительные настройки для Docker
      SPRING_PROFILES_ACTIVE: docker
      
      # DevTools настройки для hot reload
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
    ports:
      - "8083:8083"
    volumes:
      # Volume mapping для hot reload
      - ./src:/app/src
      - ./target:/app/target
      - ./src/main/resources:/app/src/main/resources
      # Копируем .env файл для загрузки переменных
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
